### ISSUE TITLE
null exception error when viewing ill-formatted attendee

### ISSUE THREAD

**Issue by micahcowan** [jashort/kumoreg#2]
If you search for and view the attendee Dana Monahan, a null reference exception is thrown (as seen in the server console output).

The message from the console output (as of commit 7e45608) is:

```
2016-04-05 22:23:59.166 ERROR 69462 --- [nio-8080-exec-9] com.vaadin.server.DefaultErrorHandler    :

java.lang.NullPointerException: null
        at org.kumoricon.view.attendee.AttendeeDetailView.enter(AttendeeDetailView.java:52) ~[classes/:na]
        at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:578) ~[vaadin-server-7.5.5.jar:7.5.5]
        at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:527) ~[vaadin-server-7.5.5.jar:7.5.5]
        at org.kumoricon.view.BaseView.navigateTo(BaseView.java:28) ~[classes/:na]
        at org.kumoricon.presenter.attendee.SearchPresenter.selectAttendee(SearchPresenter.java:44) ~[classes/:na]
        at org.kumoricon.view.attendee.SearchView.lambda$init$8b265179$1(SearchView.java:58) ~[classes/:na]
        [...]
```

The line in `AttendeeDetailView.enter()` that's called out in the backtrace is

```
detailForm.setMinorFieldsEnabled(detailForm.getAttendee().isMinor());
```

The null reference exception is due to `detailForm.getAttendee()` returning null, after which an attempt is made to call the method `.isMinor()`.

Here's `detailForm.getAttendee()`, from `AttendeeDetailForm.java`:

```
    public Attendee getAttendee() {
        try {
            fieldGroup.commit();
            return attendeeBean.getBean();
        } catch (FieldGroup.CommitException e) {
            Notification.show(e.getMessage());
        }
        return null;
    }
```

I haven't dug any further, but presumably a `CommitException` occurs within the body of the `try`, resulting in the `null` being returned. Likely the exception occurs because the phone number for Dana Monahan doesn't conform to the expectations for phone numbers (due to issue #1), and once issue #1 is fixed (and import data reloaded from scratch), this problem's symptom is likely to go away... except that I think it might be worth considering this as a separate issue, as sometimes despite one's best efforts, data can sneak into the database that doesn't match our expectations, or corruption can happen, and it's probably good for the software to handle that situation defensively.

That being said, I'm not quite sure what an appropriate reaction to this situation _should_ look like... :-/

**Comment by jashort** [comment]
I think you're right that this should be handled more gracefully.

Part of the difficulty is that there are cases where the user on that form is not allowed to make changes - so I may need to rethink how validation is done and not always validate that form.

**Comment by jashort** [comment]
I've cleaned up field validation for attendees in 6d4a916 (along with some earlier commits). 
If a user doesn't have the ability to edit a field, they shouldn't get bothered about validation on that field now. (If the field is enabled again, for example, by an override, validation gets turned back on)
